apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: mern-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080  # ✅ Explicitly define NodePort (within 30000-32767)
  type: NodePort
